In [1]:
!pip install dask

Collecting dask
  Downloading dask-2023.4.1-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 5.1 MB/s eta 0:00:00[31m5.3 MB/s eta 0:00:01
Collecting partd>=1.2.0
  Downloading partd-1.4.0-py3-none-any.whl (18 kB)
Requirement already satisfied: packaging>=20.0 in /Users/biny/miniforge3/envs/nlp/lib/python3.8/site-packages (from dask) (23.0)
Requirement already satisfied: importlib-metadata>=4.13.0 in /Users/biny/miniforge3/envs/nlp/lib/python3.8/site-packages (from dask) (6.3.0)
Collecting cloudpickle>=1.5.0
  Downloading cloudpickle-2.2.1-py3-none-any.whl (25 kB)
Collecting fsspec>=2021.09.0
  Downloading fsspec-2023.5.0-py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.1/160.1 kB 5.6 MB/s eta 0:00:00
Collecting click>=8.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 5.9 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.3.1 in /Users/biny/miniforge3/envs/nlp/lib/python3.8/site-packages (from dask) (6.0)
Collecting toolz>=0.10.0
  Downloading toolz-0.12.0-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: zipp>=0.5 in /Users/biny/miniforge3/envs/nlp/lib/python3.8/site-packages (from importlib-metadata>=4.13.0->dask) (3.15.0)
Collecting locket
  Downloading locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Installing collected packages: toolz, locket, fsspec, cloudpickle, click, partd, dask
Successfully installed click-8.1.3 cloudpickle-2.2.1 dask-2023.4.1 fsspec-2023.5.0 locket-1.0.0 partd-1.4.0 toolz-0.12.0

In [2]:
# from google.colab import drive
import pandas as pd
# drive.mount('/content/test')

In [5]:
%%time
df = pd.read_csv('/Users/biny/Desktop/workspace/practice/data/초격차/crime.csv')

CPU times: user 13.6 s, sys: 1.53 s, total: 15.2 s
Wall time: 15.3 s

In [6]:
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,12.0,61.0,08B,1165074.0,1875917.0,2015,02/10/2018 03:50:01 PM,41.815117,-87.670000,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,...,29.0,25.0,06,1138875.0,1904869.0,2015,02/10/2018 03:50:01 PM,41.895080,-87.765400,"(41.895080471, -87.765400451)"
2,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,...,8.0,44.0,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,...,35.0,21.0,18,1152037.0,1920384.0,2015,02/10/2018 03:50:01 PM,41.937406,-87.716650,"(41.937405765, -87.716649687)"
4,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,...,28.0,25.0,08A,1141706.0,1900086.0,2015,02/10/2018 03:50:01 PM,41.881903,-87.755121,"(41.881903443, -87.755121152)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7721654,12847575,JF420478,09/01/2022 05:00:00 AM,005XX W SURF ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,...,44.0,6.0,26,1172497.0,1919410.0,2022,01/03/2023 03:46:28 PM,41.934305,-87.641485,"(41.934304581, -87.641484982)"
7721655,12847801,JF420319,07/08/2022 12:00:00 AM,114XX S PRAIRIE AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,STREET,False,False,...,9.0,49.0,11,1179966.0,1828818.0,2022,01/03/2023 03:46:28 PM,41.685544,-87.616813,"(41.685543881, -87.616812541)"
7721656,12847324,JF420102,09/27/2022 11:00:00 AM,023XX E 70TH ST,0810,THEFT,OVER $500,RESIDENCE,False,False,...,5.0,43.0,06,1193181.0,1859005.0,2022,01/03/2023 03:46:28 PM,41.768068,-87.567453,"(41.768068052, -87.567452932)"
7721657,12847570,JF420427,09/03/2022 10:25:00 AM,052XX W CARMEN AVE,2021,NARCOTICS,POSSESS - BARBITURATES,RESIDENCE - YARD (FRONT / BACK),True,False,...,45.0,11.0,18,1140553.0,1933418.0,2022,01/03/2023 03:46:28 PM,41.973391,-87.758535,"(41.973391184, -87.758534512)"
7721658,12840464,JF411839,09/26/2022 07:20:00 PM,0000X N MASON AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,SIDEWALK,True,False,...,29.0,25.0,15,1136773.0,1899652.0,2022,01/03/2023 03:46:28 PM,41.880802,-87.773246,"(41.880802263, -87.773245737)"

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7721659 entries, 0 to 7721658
Data columns (total 22 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 1.2+ GB

In [16]:
%%time
# 1000줄만 읽어오기
df = pd.read_csv('/Users/biny/Desktop/workspace/practice/data/초격차/crime.csv', nrows=1000)

CPU times: user 12.6 ms, sys: 5.37 ms, total: 17.9 ms
Wall time: 16.6 ms

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    1000 non-null   int64
 1   Case Number           1000 non-null   object
 2   Date                  1000 non-null   object
 3   Block                 1000 non-null   object
 4   IUCR                  1000 non-null   object
 5   Primary Type          1000 non-null   object
 6   Description           1000 non-null   object
 7   Location Description  995 non-null    object
 8   Arrest                1000 non-null   bool
 9   Domestic              1000 non-null   bool
 10  Beat                  1000 non-null   int64
 11  District              1000 non-null   int64
 12  Ward                  1000 non-null   int64
 13  Community Area        1000 non-null   int64
 14  FBI Code              1000 non-null   object
 15  X Coordinate          945 non-null    float64
 16  Y Coordinate          945 non-null    float64
 17  Year                  1000 non-null   int64
 18  Updated On            1000 non-null   object
 19  Latitude              945 non-null    float64
 20  Longitude             945 non-null    float64
 21  Location              945 non-null    object
dtypes: bool(2), float64(4), int64(6), object(10)
memory usage: 158.3+ KB

In [18]:
%%time
# 1000줄 빼고 그 다음 애들만 읽어오기
df = pd.read_csv('/Users/biny/Desktop/workspace/practice/data/초격차/crime.csv', skiprows=[i for i in range(1,1001)])

CPU times: user 13.3 s, sys: 1.31 s, total: 14.6 s
Wall time: 14.7 s

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7720659 entries, 0 to 7720658
Data columns (total 22 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 1.2+ GB

# Chunksize로 불러오기

In [21]:
%%time
# chunksize로 가져오기
df = pd.read_csv('/Users/biny/Desktop/workspace/practice/data/초격차/crime.csv',chunksize=1000)

CPU times: user 253 ms, sys: 96.2 ms, total: 349 ms
Wall time: 348 ms

In [ ]:
df

In [ ]:
# chunksize로 불러온 애들은 dataframe이 아니기 때문에 info를 찍어볼 수 없다.  
df.info()

AttributeError: ignored

In [22]:
%%time
sum_ward = 0
for i, chunk in enumerate(df):
  if i % 10000 == 0: # chunkrk 10000개씩 될때 마다 보기
    print(f"{i+1}th execution")
  sum_ward += chunk['Ward'].sum()
print(sum_ward)

1th execution
161681984.0
CPU times: user 20.4 s, sys: 4.95 s, total: 25.3 s
Wall time: 25.3 s

# Dask Dataframe
* dask는 패키지 이름이다.

In [23]:
from dask import dataframe as ddf

In [25]:
%%time
ddf = ddf.read_csv('/Users/biny/Desktop/workspace/practice/data/초격차/crime.csv', dtype={'Community Area': 'float64', 
       'IUCR': 'object',
       'Ward': 'float64'})

CPU times: user 12.1 ms, sys: 2.75 ms, total: 14.8 ms
Wall time: 16.4 ms

In [26]:
# npartitions=28 의미 -> 데이터가 많아서 파티션을 28개로 나눠놨어. -> 이 데이터에 대한 메타 데이터를 생성해놓았다고 표현함
ddf

Dask DataFrame Structure:
                   ID Case Number    Date   Block    IUCR Primary Type Description Location Description Arrest Domestic   Beat District     Ward Community Area FBI Code X Coordinate Y Coordinate   Year Updated On Latitude Longitude Location
npartitions=28
                int64      object  object  object  object       object      object               object   bool     bool  int64    int64  float64        float64   object      float64      float64  int64     object  float64   float64   object
                  ...         ...     ...     ...     ...          ...         ...                  ...    ...      ...    ...      ...      ...            ...      ...          ...          ...    ...        ...      ...       ...      ...
...               ...         ...     ...     ...     ...          ...         ...                  ...    ...      ...    ...      ...      ...            ...      ...          ...          ...    ...        ...      ...       ...      ...
                  ...         ...     ...     ...     ...          ...         ...                  ...    ...      ...    ...      ...      ...            ...      ...          ...          ...    ...        ...      ...       ...      ...
                  ...         ...     ...     ...     ...          ...         ...                  ...    ...      ...    ...      ...      ...            ...      ...          ...          ...    ...        ...      ...       ...      ...
Dask Name: read-csv, 1 graph layer

In [27]:
ddf.info()

<class 'dask.dataframe.core.DataFrame'>
Columns: 22 entries, ID to Location
dtypes: object(10), bool(2), float64(6), int64(4)

In [28]:
# head를 찍으면 그때서야 데이터를 불러옴
ddf.head(10)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,12.0,61.0,08B,1165074.0,1875917.0,2015,02/10/2018 03:50:01 PM,41.815117,-87.670000,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,...,29.0,25.0,06,1138875.0,1904869.0,2015,02/10/2018 03:50:01 PM,41.895080,-87.765400,"(41.895080471, -87.765400451)"
2,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,...,8.0,44.0,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,...,35.0,21.0,18,1152037.0,1920384.0,2015,02/10/2018 03:50:01 PM,41.937406,-87.716650,"(41.937405765, -87.716649687)"
4,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,...,28.0,25.0,08A,1141706.0,1900086.0,2015,02/10/2018 03:50:01 PM,41.881903,-87.755121,"(41.881903443, -87.755121152)"
5,10224742,HY411435,09/05/2015 10:55:00 AM,082XX S LOOMIS BLVD,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,...,21.0,71.0,05,1168430.0,1850165.0,2015,02/10/2018 03:50:01 PM,41.744379,-87.658431,"(41.744378879, -87.658430635)"
6,10224743,HY411629,09/04/2015 06:00:00 PM,021XX W CHURCHILL ST,0620,BURGLARY,UNLAWFUL ENTRY,RESIDENCE-GARAGE,False,False,...,32.0,24.0,05,1161628.0,1912157.0,2015,02/10/2018 03:50:01 PM,41.914636,-87.681631,"(41.914635603, -87.681630909)"
7,10224744,HY411605,09/05/2015 01:00:00 PM,025XX W CERMAK RD,0860,THEFT,RETAIL THEFT,GROCERY FOOD STORE,True,False,...,25.0,31.0,06,1159734.0,1889313.0,2015,09/17/2015 11:37:18 AM,41.851989,-87.689219,"(41.851988885, -87.689219118)"
8,10224745,HY411654,09/05/2015 11:30:00 AM,031XX W WASHINGTON BLVD,0320,ROBBERY,STRONGARM - NO WEAPON,STREET,False,True,...,27.0,27.0,03,1155536.0,1900515.0,2015,02/10/2018 03:50:01 PM,41.882814,-87.704326,"(41.88281374, -87.704325717)"
9,11645836,JC212333,05/01/2016 12:25:00 AM,055XX S ROCKWELL ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,15.0,63.0,11,NaN,NaN,2016,04/06/2019 04:04:43 PM,NaN,NaN,NaN

In [34]:
%%time

# pandas보다 반은 빠름
ddf_sum = ddf['Ward'].sum().compute()

CPU times: user 15.9 s, sys: 2.71 s, total: 18.6 s
Wall time: 10.7 s

In [35]:
ddf_sum

161681984.0

In [37]:
# 뒤에 compute()를 붙여주지 않으면 값이 안나옴. sum을 할 준비만 함 
ddf['Ward'].sum()

dd.Scalar<series-..., dtype=float64>